- id: django-no-auto-migrations
  name: No auto-named migrations
  entry: please provide a descriptive name for migrations
  language: fail
  files: .*/migrations/.*_auto_.*\.py$
- id: django-url-trailing-slash
  name: No missing trailing slashes in URLs
  description: Warn if a Django URL doesn't end in a /
  entry: >
    (?x)(
      \bpath\(\s*["'][^"']+(?<!\/)["'],|
      (url|re_path)\(\s*r?["'][^'"]+(?<!\/\$)(?<!\/)["'],
    )
  language: pygrep
  types: [python]
  files: urls.py$
- id: django-invalid-perm
  name: No invalid Permission codenames
  description: Warn if `has_perm` or `permission_required` uses an invalid perm
  entry: (has_perm|@permission_required)\(["'][^\."']+["']\)
  language: pygrep
  types: [python]
