name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: setup-python
        uses: actions/setup-python@v2

      - id: cache-pip
        uses: actions/cache@v2
        with:
          path: venv
          key: pip-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements/test.txt') }}
          restore-keys: pip-${{ steps.setup-python.outputs.python-version }}-

      - if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt

      - run: |
          . venv/bin/activate
          pytest
